{
    "openapi": "3.0.0",
    "info": {
      "title": "Nobi Mission",
      "version": "1.0.0"
    },
    "servers": [
      {
        "url": "https://dev-nobi-mission.honestmining.org",
        "description": "Development"
      },
      {
        "url": "http://localhost:3030",
        "description": "Localhost"
      }
    ],
    "tags": [
      {
        "name": "hodl"
      },
      {
        "name": "hodl > V1"
      }
    ],
    "paths": {
		"/v1/hodl/cutoff": {
			"post": {
				"tags": [
					"hodl > V1"
				],
				"summary": "Cutoff",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "object"
								},
								"example": {
                                    "status": true,
                                    "service": "Hodl Service",
                                    "message": "Successfully",
                                    "data": {
                                        "total_users": 10
                                    },
                                    "created_at": 1676991565117
                                }
							}
						}
					},
                    "422": {
						"description": "Unprocessable Entity"
					},
                    "500": {
						"description": "Internal Server Error"
					}
				}
			}
		},
        "/v1/hodl/cutoff/reminder": {
			"post": {
				"tags": [
					"hodl > V1"
				],
				"summary": "Cutoff Notification Reminder",
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "object"
								},
								"example": {
                                    "status": true,
                                    "service": "Hodl Service",
                                    "message": "Successfully",
                                    "data": {
                                        "total_users": 9
                                    },
                                    "created_at": 1676991565117
                                }
							}
						}
					},
                    "422": {
						"description": "Unprocessable Entity"
					},
                    "500": {
						"description": "Internal Server Error"
					}
				}
			}
		},
      "/v1/hodl/inquiry": {
        "post": {
          "tags": [
            "hodl > V1"
          ],
          "summary": "Inquiry",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "promo_code": "HODL-CHALLENGE-22"
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object"
                  },
                  "example": {
                    "status": true,
                    "service": "Hodl Service",
                    "message": "Successfully",
                    "data": {
                      "id": 1,
                      "promo_code": "HODL-CHALLENGE-22",
                      "coin_id": 531,
                      "ticker": "HNST",
                      "min_amount": 50.525,
                      "days": 10,
                      "is_active": true,
                      "start_date": 1675203383,
                      "end_date": 1678659383,
                      "created_at": "2023-02-08T03:02:12.000Z",
                      "updated_at": "2023-02-28T02:41:34.000Z"
                    },
                    "created_at": 1677552258117
                  }
                }
              }
            },
            "422": {
                "description": "Unprocessable Entity",
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object"
                    },
                    "example": {
                      "status": false,
                      "service": "hodl.inquiry",
                      "message": "promo code not found",
                      "data": {
                        "promo_code": "HODL-CHALLENGE-99"
                      },
                      "created_at": 1677552292616
                    }
                  }
                }
            },
            "500": {
                "description": "Internal Server Error"
            }
          }
        }
      },
      "/v1/hodl/inquiry/transaction": {
        "post": {
          "tags": [
            "hodl > V1"
          ],
          "summary": "Inquiry Transaction",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "user_id": 20480,
                    "promo_code": "HODL-CHALLENGE-22"
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object"
                  },
                  "examples": {
                    "example-0": {
                      "summary": "Success",
                      "value": {
                        "status": true,
                        "service": "Hodl Service",
                        "message": "Successfully",
                        "data": {
                            "id": 2,
                            "user_id": 20480,
                            "trx_id": "4c06746b-5bbse-4as6b6-92esssssss1-c18c38447745",
                            "remaining_days": 5,
                            "promo_code": "HODL-CHALLENGE-22",
                            "status": "on progress"
                        },
                        "created_at": 1677551469944
                      }
                    },
                    "example-1": {
                      "summary": "User Not Found",
                      "value": {
                        "status": true,
                        "service": "Hodl Service",
                        "message": "Successfully",
                        "data": {
                            "id": 0,
                            "user_id": 2048,
                            "trx_id": null,
                            "remaining_days": 10,
                            "promo_code": "HODL-CHALLENGE-22",
                            "status": "waiting"
                        },
                        "created_at": 1677551638747
                      }
                    }
                  }
                }
              }
            },
            "422": {
                "description": "Unprocessable Entity"
            },
            "500": {
                "description": "Internal Server Error"
            }
          }
        }
      },
      "/v1/hodl/redeem": {
        "post": {
          "tags": [
            "hodl > V1"
          ],
          "summary": "Redeem",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "user_id": 20480,
                    "promo_code": "HODL-CHALLENGE-22"
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object"
                  },
                  "example": {
                    "status": true,
                    "service": "Hodl Service",
                    "message": "Successfully",
                    "data": true,
                    "created_at": 1660806082350
                  }
                }
              }
            },
            "422": {
                "description": "Unprocessable Entity"
            },
            "500": {
                "description": "Internal Server Error"
            }
          }
        }
      },
      "/v1/hodl/generate": {
        "post": {
          "tags": [
            "hodl > V1"
          ],
          "summary": "Store/Update Hodl",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "promo_code": "HODL-CHALLENGE-22",
                    "coin_id": 531,
                    "ticker": "HNST",
                    "min_amount": 50.525,
                    "days": 10,
                    "is_active": true,
                    "start_date": 1675203383,
                    "end_date": 1677622583
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object"
                  },
                  "example": {
                    "status": true,
                    "service": "Hodl Service",
                    "message": "Successfully",
                    "data": {
                      "id": 12,
                      "promo_code": "HODL-CHALLENGE-22",
                      "coin_id": 531,
                      "ticker": "HNST",
                      "min_amount": 50.525,
                      "days": 10,
                      "is_active": true,
                      "start_date": 1675203383,
                      "end_date": 1677622583,
                      "created_at": "2016-07-15T20:23:01.804Z",
                      "updated_at": "2016-07-15T20:23:01.804Z"
                    },
                    "created_at": 1660806082350
                  }
                }
              }
            },
            "422": {
                "description": "Unprocessable Entity",
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object"
                    },
                    "example": {
                        "status": false,
                        "service": "Request Validation",
                        "message": "The requested parameter is invalid",
                        "data": [
                          {
                            "field": "promo_code",
                            "message": "must be filled in, not allowed (empty, null, undefined or NaN)"
                          },
                          {
                            "field": "coin_id",
                            "message": "must be filled in, not allowed (empty, null, undefined or NaN)"
                          },
                          {
                            "field": "ticker",
                            "message": "must be filled in, not allowed (empty, null, undefined or NaN)"
                          },
                          {
                            "field": "min_amount",
                            "message": "must be filled in, not allowed (empty, null, undefined or NaN)"
                          },
                          {
                            "field": "days",
                            "message": "must be filled in, not allowed (empty, null, undefined or NaN)"
                          },
                          {
                            "field": "is_active",
                            "message": "must be filled in, not allowed (empty, null, undefined or NaN)"
                          },
                          {
                            "field": "start_date",
                            "message": "must be filled in, not allowed (empty, null, undefined or NaN)"
                          },
                          {
                            "field": "end_date",
                            "message": "must be filled in, not allowed (empty, null, undefined or NaN)"
                          }
                        ],
                        "created_at": 1677567169346
                      }
                  }
                }
            },
            "500": {
                "description": "Internal Server Error"
            }
          }
        }
      },
      "/v1/hodl/generate/transaction": {
        "post": {
          "tags": [
            "hodl > V1"
          ],
          "summary": "Generate Hodl Transaction",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "user_id": 20480,
                    "promo_code": "HODL-CHALLENGE-22",
                    "trx_id": "4c06746b-5bbse-4as6b6-92esssssss1-c18c38447745"
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object"
                  },
                  "example": {
                    "status": true,
                    "service": "Hodl Service",
                    "message": "Successfully",
                    "data": {
                      "id": 4,
                      "hodl_id": 12,
                      "hodl_status_id": 1,
                      "user_id": 20480,
                      "trx_id": "4c06746b-5bbse-4as6b6-92esssssss1-c18c38447745",
                      "remaining_days": 10,
                      "created_at": "2022-07-19T20:23:01.804Z",
                      "updated_at": "2022-07-19T20:23:01.804Z",
                      "hodl": {
                        "id": 12,
                        "promo_code": "HODL-CHALLENGE-22",
                        "coin_id": 531,
                        "ticker": "HNST",
                        "min_amount": 50.525,
                        "days": 10,
                        "is_active": true,
                        "start_date": 1675203383,
                        "end_date": 1677622583,
                        "created_at": "2022-07-15T20:23:01.804Z",
                        "updated_at": "2022-07-15T20:23:01.804Z"
                      },
                      "hodl_status": {
                        "id": 1,
                        "name": "waiting",
                        "desc": "Waiting",
                        "created_at": "2022-07-15T20:23:01.804Z",
                        "updated_at": "2022-07-19T20:23:01.804Z"
                      }
                    },
                    "created_at": 1660806082350
                  }
                }
              }
            },
            "422": {
                "description": "Unprocessable Entity",
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "object"
                    },
                    "examples": {
                        "example-0": {
                            "summary": "Request Validation",
                            "value": {
                                "status": false,
                                "service": "Request Validation",
                                "message": "The requested parameter is invalid",
                                "data": [
                                {
                                    "field": "user_id",
                                    "message": "must be filled in, not allowed (empty, null, undefined or NaN)"
                                },
                                {
                                    "field": "promo_code",
                                    "message": "must be filled in, not allowed (empty, null, undefined or NaN)"
                                },
                                {
                                    "field": "trx_id",
                                    "message": "must be filled in, not allowed (empty, null, undefined or NaN)"
                                }
                                ],
                                "created_at": 1677567324562
                            }
                        },
                        "example-1": {
                            "summary": "Unable to claim",
                            "value": {
                                "status": false,
                                "service": "GENERATE HODL TRANSACTION SERVICE",
                                "message": "unable to claim",
                                "data": {
                                  "user_id": 20480,
                                  "hodl": {
                                    "id": "21",
                                    "promo_code": "HODL-CHALLENGE-5",
                                    "coin_id": "531",
                                    "ticker": "HNST",
                                    "min_amount": "50.525000000000",
                                    "days": 7,
                                    "is_active": true,
                                    "start_date": 1675234799,
                                    "end_date": 1676530799,
                                    "created_at": "2023-02-28T07:07:44.000Z",
                                    "updated_at": "2023-02-28T07:07:44.000Z"
                                  }
                                },
                                "created_at": 1677568072068
                            }
                        }
                    }
                  }
                }
            },
            "500": {
                "description": "Internal Server Error"
            }
          }
        }
      }
    },
    "components": {}
  }